/**
 * Metric Grounding & Scheme Name Validator
 * Ensures that LLM responses do not contain fabricated statistics, incorrect scores,
 * or non-existent scheme rules.
 */

// Common numbers that are safe to use in explanations without strict grounding
const SAFE_NUMBERS = new Set([
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 18, 20, 21, 23, 25, 30, 40, 50, 60, 70, 80, 90, 100,
  2011, 2026, 80 // e.g. Section 80C
]);

/**
 * Validates generated LLM text against the retrieved context dataset
 * @param {string} generatedText - The response generated by the LLM
 * @param {object} retrievedContext - The budgeted data retrieved from the DB
 * @param {Array<string>} allAllowedSchemeCodes - List of all valid scheme codes in the DB
 * @returns {object} - { success: boolean, flagged: boolean, warnings: Array<string>, verifiedMetrics: Array<string> }
 */
export function validateMetricsGrounding(generatedText, retrievedContext, allAllowedSchemeCodes = []) {
  const warnings = [];
  const verifiedMetrics = [];
  const text = generatedText || "";

  // 1. Gather all target numbers from the context
  const contextNumbers = [];
  const contextKeyValues = {};

  function extractNumbersFromObject(obj) {
    if (!obj) return;
    for (const [key, value] of Object.entries(obj)) {
      if (typeof value === 'number') {
        contextNumbers.push(value);
        contextKeyValues[key] = value;
      } else if (typeof value === 'string') {
        const parsed = parseFloat(value.replace(/[^0-9.]/g, ''));
        if (!isNaN(parsed)) {
          contextNumbers.push(parsed);
        }
      } else if (typeof value === 'object') {
        extractNumbersFromObject(value);
      }
    }
  }

  extractNumbersFromObject(retrievedContext);

  // 2. Parse numbers from the generated text (ignoring percentage signs and formatting)
  const numberRegex = /\b\d+(?:\.\d+)?\b/g;
  let match;
  const parsedNumbers = [];

  while ((match = numberRegex.exec(text)) !== null) {
    const val = parseFloat(match[0]);
    if (!isNaN(val)) {
      parsedNumbers.push({
        value: val,
        raw: match[0],
        index: match.index
      });
    }
  }

  // 3. Perform Metric Checks
  for (const item of parsedNumbers) {
    const num = item.value;
    
    // Ignore standard boilerplate index/age/percentage numbers
    if (SAFE_NUMBERS.has(num)) continue;
    
    // Check if the number matches a context metric exactly or close with rounding (within 2% margin)
    let isMatch = false;
    let closestMetric = null;
    let minDiff = Infinity;

    for (const metric of contextNumbers) {
      if (metric === 0) continue;
      const diff = Math.abs(metric - num) / metric;
      if (diff < minDiff) {
        minDiff = diff;
        closestMetric = metric;
      }
    }

    if (minDiff <= 0.05) { // 5% allowance for rounding (e.g. "18,000" for "18,163")
      isMatch = true;
      verifiedMetrics.push(`${item.raw} (close to context value ${closestMetric})`);
    }

    // Special exact checks for decimal rates or scores if present
    // E.g. Interest rate (like 8.2 or 7.5) should be matched exactly or not flag if it's close
    if (!isMatch) {
      // If context has interest rates, match them exactly
      const isInterestRateHallucination = contextKeyValues.interestRate !== undefined && 
        Math.abs(contextKeyValues.interestRate - num) > 0.01 &&
        (item.raw.includes(".") || (num > 2 && num < 15)); // likely an interest rate attempt
        
      if (isInterestRateHallucination) {
        warnings.push(`Potential interest rate or decimal metric mismatch: "${item.raw}" does not match context rate "${contextKeyValues.interestRate}%"`);
      } else {
        warnings.push(`Metric grounding warning: "${item.raw}" could not be verified against demographic or DSS metrics.`);
      }
    }
  }

  // 4. Validate Scheme codes / names in text
  // Check if text mentions scheme acronyms that are not in our list
  if (allAllowedSchemeCodes.length > 0) {
    // Look for uppercase words of length 2-15 that look like acronyms
    const acronymRegex = /\b[A-Z]{2,15}\b/g;
    const acronyms = text.match(acronymRegex) || [];
    
    // Allowed words that might look like acronyms but are safe
    const ignoredAcronyms = new Set(["DBT", "KYC", "PAN", "SMS", "DSS", "III", "II", "IV", "USD", "INR", "EEE", "PO", "POSB"]);

    for (const ac of acronyms) {
      if (ignoredAcronyms.has(ac)) continue;
      if (!allAllowedSchemeCodes.includes(ac)) {
        warnings.push(`Scheme verification error: Mentioned scheme "${ac}" is not present in the DSS database.`);
      }
    }
  }

  // 5. Enforce Explainability: prevent vague statements
  const vaguePatterns = [
    /this scheme appears suitable/i,
    /this scheme is suitable/i,
    /this appears suitable/i,
    /appears suitable/i
  ];

  for (const pattern of vaguePatterns) {
    if (pattern.test(text)) {
      warnings.push(`Explainability violation: Response contains a generic suitabiliy statement ("${text.match(pattern)[0]}"). Explanations must justify recommendations using specific metrics.`);
    }
  }

  return {
    success: warnings.length === 0,
    flagged: warnings.length > 0,
    warnings,
    verifiedMetrics
  };
}
